stages:
  - prepare
  - build
  - test
#  - package

cache:
  untracked: true
  paths:
    - build
    - external

before_script:
 - apt-get update --yes
 - apt-get install --yes cmake gcc g++ clang

# Since we are using cache to persist all data, we need to clean in the first
# step.
prepare:
  stage: prepare
  script:
    - git reset --hard HEAD
    - git clean -d -f -x
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=./
    - make external-update-all

build:
  stage: build
  script:
    - cd build
    - make
    - make install
    - make run

test:
  stage: test
  script:
    - cd build
    - make unit_testsuite
    - make test

#package:
#  stage: package
#  artifacts:
#    expire_in: 1 week
#    paths:
#      - build/out/
#  script:
#    - cd build
#    - make package
